### PR TITLE
Typing fixes

### PR DESCRIPTION
**Pull request by justmobilize**
In this update:

1. Run `isort` to organize imports
2. When `TYPE_CHECKING` import types from `circuitpython-stubs`
3. define `_FakeSSLContext` in `socket.py` to simplify typing in other libraries

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]

**Review by dhalbert — COMMENTED** [review]
Now that you added the `import`s, can you actually remove some of the double-quotes around typenames, like `"rgbmatrix.RGBMatrix"` -> `rgbmatrix.RGBMatrix`? Or is that still not possible because these are not in CPython?

**Comment by justmobilize** [comment]
@dhalbert I removed a random selection and didn't get any additional errors... So looks like we should. Would you want that in this PR or a follow up?

**Comment by dhalbert** [comment]
Go ahead and do it in this one.

**Comment by justmobilize** [comment]
@dhalbert looks like we can't. Since it's not defined except for typing it fails install (see the checks)

**Comment by justmobilize** [comment]
link here: https://github.com/adafruit/Adafruit_CircuitPython_Typing/actions/runs/7848800701/job/21420726625?pr=35

**Pull request merged**
