### PR TITLE
Made changes to bring library closer to cookiecutter

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by kattni — APPROVED** [review]

**Comment by dhalbert** [comment]
Maybe this library should be called `typing_circuitpython`, and the repo named `Adafruit_CircuitPython_Typing_CircuitPython?? That would get rid of the naming inconsistencies.

**Comment by evaherrada** [comment]
Just for adabot. However I could also make adabot be ok with examples following the format of: CircuitPython_LIBNAME_EXAMPLENAME.py

**Comment by dhalbert** [comment]
> Maybe this library should be called `typing_circuitpython`, and the repo named `Adafruit_CircuitPython_Typing_CircuitPython`?? That would get rid of the naming inconsistencies.

I'm willing to keep having the example renamed and make renaming the library a long-term issue.

**Comment by evaherrada** [comment]
Yeah that could work, although I personally would want to avoid that as I think it doesn't look great, but I understand why it would make sense to do

**Pull request merged**
